### ISSUE TITLE
Can we use this to run android espresso test also?

### ISSUE THREAD

**Issue by santoshgistto** [yunusmete/openstf-java-client#1]

**Comment by yunusmete** [comment]
If you have a structure that runs test on specified device and yes, you can.

**Comment by santoshgistto** [comment]
@yunusmete thanks for response. automation testing world.
structure means stf setup?

**Comment by yunusmete** [comment]
No, you can claim a phone which you want with STF. You must assign test to phone. Just it!

**Comment by santoshgistto** [comment]
if any Example ? it would be great.

**Comment by yunusmete** [comment]
Sorry, I don't have any.

**Comment by santoshgistto** [comment]
@yunusmete  thank you, as i saw in  AppiumTest class your onto using udid to start the particular device and are we need to start multiple appium servers?

**Comment by zhujie616** [comment]
could you give some examples？maybe you can give some document on how to use it

**Comment by yunusmete** [comment]
@zhujie616 The library is about device farm, so I have examples with Appium only. You can see it there: https://github.com/yunusmete/openstf-java-client/blob/master/src/test/java/STF.java
So maybe you can adapt it to Espresso test.

**Comment by yunusmete** [comment]
@santoshgistto No, you don't have to. If you are not trying to run tests parallel, you can run all test with single Appium instance.
